image: alpine:3.5

variables:
  DOCKER_DRIVER: overlay
  DOCKER_IMAGE: mrandri19/registro-react:$CI_COMMIT_REF_NAME

stages:
  - build
  - push
  - deploy

.node_image: &node_image
  image: danielemonteleone/node-alpine:latest

.npm_cache: &npm_cache
  cache:
    paths:
      - node_modules

webpack:
  stage: build
  <<: *node_image
  <<: *npm_cache
  before_script:
    - npm install
  script:
    - npm run build-prod
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - node_modules/
      - dist/
    expire_in: 1d

.docker: &docker
  services:
    - docker:17.03.1-ce-dind
  image: "docker:17.03.1-ce"
  before_script:
    - docker info
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

docker:
  stage: push
  dependencies:
    - webpack
  <<: *docker
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
